"""empty message

Revision ID: 260c7f6df80e
Revises: 4cd381f6cc9d
Create Date: 2024-03-31 22:37:15.832442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '260c7f6df80e'
down_revision = '4cd381f6cc9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
